package gui;

import util.FileUtil;

/**
 * The about page with information on the project
 * @author Gian
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextPane1.setText(FileUtil.readFile("UserManual/About.html"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setTitle("About");
        setMinimumSize(new java.awt.Dimension(400, 335));
        setPreferredSize(new java.awt.Dimension(400, 335));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 335));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 335));

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setMinimumSize(new java.awt.Dimension(400, 335));
        jTextPane1.setPreferredSize(new java.awt.Dimension(335, 335));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
