package gui;

import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import util.FileUtil;

/**
 *
 * @author Gian
 */
public class UserManual extends javax.swing.JFrame {

    /**
     * Creates new User Manual window
     */
    public UserManual() {
        initComponents();
        // Display the window at the center of the screen (fixes error on linux)
        setLocationRelativeTo(null);
        // Load files in the Manual
        loadManual("UserManual");
    }

    /**
     * Loads .html files in a folder and displays them in the window.
     *
     * @param folderpath the path to the folder
     */
    public void loadManual(String folderpath) {
        // Check if folder Exists
        if(!FileUtil.folderExists(folderpath)) return;
        for (File f : FileUtil.filesIn(folderpath)) {
            // For each file in the given folder
            if (f.getName().endsWith(".html")) {
                // If it's an html file, add it to the UserManual tabs
                addHtmlTab(f.getName().replace(".html", ""), FileUtil.readFile(f));
            }
        }
    }

    /**
     * Adds a new tab containing the given HTML text.
     *
     * @param name the name of the tab
     * @param text the HTML to put in the tab
     */
    public void addHtmlTab(String name, String text) {
        JScrollPane pane = new JScrollPane();
        JTextPane htmlText = new JTextPane();
        pane.setViewportView(htmlText);
        htmlText.setContentType("text/html");
        htmlText.setText(text);
        htmlText.setEditable(false);
        tabs.addTab(name, pane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();

        setTitle("User Manual");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
